service: serverless-chrome-package-lambda-test

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  environment:
    DEBUG: "*"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::backpack-lambda/*"

package:
  exclude:
    - src/**
    - node_modules/**
    - '!node_modules/lighthouse/**'
    - '!node_modules/chrome-remote-interface/**'
    - '!node_modules/mkdirp/**'
    - '!node_modules/debug/**'
    - '!node_modules/rimraf/**'
    - '!node_modules/ms/**'
    - '!node_modules/aws-sdk/**'
  include:
    - lib/**

functions:
  test:
    description: serverless-headless/lambda test
    memorySize: 1536
    timeout: 30
    handler: lib/handler.test

    events:
      - http:
          path: package/lambda/test
          method: get

  screenshot:
    description: serverless-headless/lambda screenshot
    memorySize: 1536
    timeout: 30
    handler: lib/handler.screenshot

    events:
      - http:
          path: package/lambda/screenshot
          method: get
